services:
  backend: 
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3030:3030"
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

 